import Head from "next/head";
import React from "react";
import NavBar from "../NavBar";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Convene</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="lg:mt-[7rem]">{children}</main>
    </div>
  );
};

export default Layout;
