import { useState } from "react";
import Head from "next/head";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const ForgotPassword = () => {
  const [email, setEmail] = useState("");

  const forgotPassword = async () => {
    try {
      // Send a request to your "Reset Password" API route
      const response = await fetch("/api/users/forgotpassword", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        // Password reset successful, you can redirect the user to a success page
        toast.success(data.message);
      } else {
        // Handle password reset error, e.g., display an error message to the user
        toast.error("Password reset failed");
      }
    } catch (error) {
      console.error("An error occurred:", error);
    }
  };


  return (
    <div>
      <Head>
        <title>Forgot Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        <h1 >
          Forgot Password
        </h1>

        <div >
          <div >
            <input
              type="email"
              placeholder=""
              value={email}
            
              onChange={(e) => setEmail(e.target.value)}
            />
            <label
         
            >
              E-mail
            </label>
          </div>
          <button
            onClick={forgotPassword}
         
          >
            Forgot Password
          </button>
        </div>
      </div>
    </div>
  );
};

export default ForgotPassword;